server:
    port: 8080 # ?? ??(???? 8080)
spring:
    profiles:
        active: dev # ????? dev ???? ??
    thymeleaf:
        cache: false # ???? ?? ??
        prefix: file:src/main/resources/templates/ # ???? ?? ??(? ??? ?? ??)
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: true
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/sbb?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
        username: yjs
        password: yjs1234
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
                default_batch_fetch_size: 100